### ISSUE TITLE
[FEATURE] Fix dependency and upgradation issues

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_callback#66]
**Describe the bug**
After upgrading the flask and dependent packages to the latest version. there are some issues with the latest changes. We need to fix these issues to make the system work fine.

**Expected behavior**
- [x] All the functionality should work fine without any errors

**Screenshots**
NA

**Additional context**
We have upgraded Flask and related packages to the latest version. There are some issues related to the DB operations. We need to fix them

**Acceptance Criteria**
- [x] All the errors are fixed

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
**Found the following issues while upgrading the flask dependency**
 
- [x] Some packages were dependent on the Flask upgraded version ie. Flask 3.0.0 so we upgraded the following packages to their required versions
    - requests==2.31.0
    - SQLAlchemy==2.0.23
    - Jinja2==3.1.2
    - MarkupSafe==2.1.1
    - psycopg2==2.9.9
- The webhook payload we are getting in **formdata** format - the older version of flask was able to handle it, it broke after upgrading the Flask version. Worked in fixing and  - https://github.com/DostEducation/RP_IVR_callback/commit/6f8e8698233126e22910e907e6382f22ad483ebc
- [x] Database connection issue with staging sever - After the package upgraded the DB initialization was throwing error **RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.**  Which needed some changes in the sequence of the imports.


Closing the issue as completed and released on production.

**Comment by Satendra-SR** [comment]
### Details on over-effort spending in this issue:


1. After the Flask upgrade - as expected, we ran the application on the local machine to see if anything was broken due to the upgrade. On testing, we found there are some dependencies which need to be upgraded to a certain version to make it run again - sharing a few examples below. We had to upgrade each version sequentially to check which particular version is required with upgraded Flask version - **7-9 hours**
    - requests==2.31.0
    - SQLAlchemy==2.0.23
    - Jinja2==3.1.2
    - MarkupSafe==2.1.1
    - psycopg2==2.9.9
2. The webhook payload we are getting in `FormData` format - the older version of Flask was able to handle it, it broke after upgrading the Flask version. Fixed it after having some debugging and a few round of testing. This became a bit difficult as we had to rely on webhook payload stored in our database as there is no way to test it from KooKoo - https://github.com/DostEducation/RP_IVR_callback/commit/6f8e8698233126e22910e907e6382f22ad483ebc - **3-5 hours**
3. With upgraded version of Flask and other related dependencies - we found the database connection is not happening - with the error -  `**RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead**` and SQLALCHEMY_TRACK_MODIFICATIONS - Fixed it - **2-3 hours**



**Summary:**
- The main cause of missing estimates here is technical challenges and unexpected scenarios while deploying and testing changes in staging and production environments.
- The Effort are in range. The actual efforts are in between.

**Comment by Satendra-SR** [comment]
### Details on over-effort spending in this issue:

1. After the Flask upgrade 
    - As expected, we ran the application on the local machine to see if anything was broken due to the upgrade. On testing, we found some dependencies that need to be upgraded to a certain version to make it run again.
    - We had to upgrade each version sequentially to check which particular version was compatible with the upgraded Flask version - it took some time 
    - Sharing a few examples below.  - **4 hours**
        - SQLAlchemy==2.0.23
        - psycopg2==2.9.9
2. With the upgraded version of Flask and other related dependencies - we found the database connection is not happening - with the error -  `**RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead**`  - Fixed it - **4 hour**
3. **Post production release issue** - When we deployed the application on production, we started getting errors for every webhook request from Kookoo. Since Kookoo is an external app, it was not possible to encounter or anticipate those errors on local and staging environment as Kookoo only makes the request on the Production environment. https://github.com/DostEducation/RP_IVR_callback/commit/6f8e8698233126e22910e907e6382f22ad483ebc - **7 hours**


**Summary:**
- The main cause of missing estimates here is technical challenges and unexpected scenarios and dependency on KooKoo while deploying and testing changes in staging and production environments.

**Comment by Sachinbisht27** [comment]
**Explanation of efforts spent -**

1. This feature is for processing Kookoo webhook. There are known testing limitation with Kookoo integration and we have an open pending request to allow testing on staging.
2. The issue was fixed on local and the application was workig fine within 8 hours.
3. On local, the testing was done with Kookoo payload we have in database. As we used as a workaround to test kookoo webhook on local.
4. Ideally, on production release, becuase we tested using the Kookoo payload, there should be no bug. But unfortunately, we got errors.
5. The extra 7 hours were to fix those issues. The trail of this work was logged on through Github PR.
6. I have added the detailed breakdown of those Kookoo fixes in the Gitub today.
7. Here also, we were tracking these hours regularly on the same day in ColoredCow timesheet but missed updating it in GitHub. I verified the same dates entry in the CC timesheet via Google sheet history.
